/********************************************************************************
 * Copyright (c) 2025 CrossBreeze.
 ********************************************************************************/
/* eslint-disable max-len */
/** @jsx svg */

import { svg } from '@eclipse-glsp/client';

export const icons = {
   ApplicationCollaboration: <use href='icons/application-collaboration.svg#root' />,
   ApplicationComponent: <use href='icons/application-component.svg#root' />,
   ApplicationEvent: <use href='icons/application-event.svg#root' />,
   ApplicationFunction: <use href='icons/application-function.svg#root' />,
   ApplicationInterface: <use href='icons/application-interface.svg#root' />,
   ApplicationInteraction: <use href='icons/application-interaction.svg#root' />,
   ApplicationProcess: <use href='icons/application-process.svg#root' />,
   ApplicationService: <use href='icons/application-service.svg#root' />,
   Artifact: <use href='icons/artifact.svg#root' />,
   Assessment: <use href='icons/assessment.svg#root' />,
   BusinessActor: <use href='icons/business-actor.svg#root' />,
   BusinessCollaboration: <use href='icons/business-collaboration.svg#root' />,
   BusinessEvent: <use href='icons/business-event.svg#root' />,
   BusinessFunction: <use href='icons/business-function.svg#root' />,
   BusinessInteraction: <use href='icons/business-interaction.svg#root' />,
   BusinessInterface: <use href='icons/business-interface.svg#root' />,
   BusinessObject: <use href='icons/business-object.svg#root' />,
   BusinessProcess: <use href='icons/business-process.svg#root' />,
   BusinessRole: <use href='icons/business-role.svg#root' />,
   BusinessService: <use href='icons/business-service.svg#root' />,
   Capability: <use href='icons/capability.svg#root' />,
   Constraint: <use href='icons/constraint.svg#root' />,
   CommunicationNetwork: <use href='icons/communication-network.svg#root' />,
   Contract: <use href='icons/contract.svg#root' />,
   CourseOfAction: <use href='icons/course-of-action.svg#root' />,
   DataObject: <use href='icons/data-object.svg#root' />,
   Deliverable: <use href='icons/deliverable.svg#root' />,
   Device: <use href='icons/device.svg#root' />,
   DistributionNetwork: <use href='icons/distribution-network.svg#root' />,
   Driver: <use href='icons/driver.svg#root' />,
   Equipment: <use href='icons/equipment.svg#root' />,
   Facility: <use href='icons/facility.svg#root' />,
   Gap: <use href='icons/gap.svg#root' />,
   Goal: <use href='icons/goal.svg#root' />,
   Grouping: <use href='icons/grouping.svg#root' />,
   ImplementationEvent: <use href='icons/implementation-event.svg#root' />,
   Location: <use href='icons/location.svg#root' />,
   Material: <use href='icons/material.svg#root' />,
   Meaning: <use href='icons/meaning.svg#root' />,
   Node: <use href='icons/node.svg#root' />,
   Outcome: <use href='icons/outcome.svg#root' />,
   Path: <use href='icons/path.svg#root' />,
   Plateau: <use href='icons/plateau.svg#root' />,
   Principle: <use href='icons/principle.svg#root' />,
   Product: <use href='icons/product.svg#root' />,
   Requirement: <use href='icons/requirement.svg#root' />,
   Representation: <use href='icons/representation.svg#root' />,
   Resource: <use href='icons/resource.svg#root' />,
   Stakeholder: <use href='icons/stakeholder.svg#root' />,
   SystemSoftware: <use href='icons/system-software.svg#root' />,
   TechnologyCollaboration: <use href='icons/technology-collaboration.svg#root' />,
   TechnologyEvent: <use href='icons/technology-event.svg#root' />,
   TechnologyFunction: <use href='icons/technology-function.svg#root' />,
   TechnologyInteraction: <use href='icons/technology-interaction.svg#root' />,
   TechnologyInterface: <use href='icons/technology-interface.svg#root' />,
   TechnologyProcess: <use href='icons/technology-process.svg#root' />,
   TechnologyService: <use href='icons/technology-service.svg#root' />,
   Value: <use href='icons/value.svg#root' />,
   ValueStream: <use href='icons/value-stream.svg#root' />,
   WorkPackage: <use href='icons/work-package.svg#root' />
};
