# GitPod configuration for bigArchiMate.

tasks:
  # To have the OS dependencies for bigArchiMate installed execute the following commands in the GitPod workspace once:
  - before: |
      sudo apt-get -y install libsecret-1-dev libxkbfile-dev
      nvm install 16.20.0
      pyenv install -s 3.11.4
      pyenv global 3.11.4
    # Download dependencies
    init: yarn
    # Build and watch the source code.
    command: yarn watch
